# Generated by Django 4.2.7 on 2025-12-05 17:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Card',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('word', models.CharField(max_length=200, verbose_name='Слово')),
                ('translation', models.CharField(max_length=200, verbose_name='Перевод')),
                ('example', models.TextField(blank=True, null=True, verbose_name='Пример использования')),
                ('note', models.TextField(blank=True, null=True, verbose_name='Заметка')),
                ('level', models.CharField(choices=[('beginner', 'Начальный'), ('intermediate', 'Средний'), ('advanced', 'Продвинутый')], default='beginner', max_length=20, verbose_name='Уровень')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cards', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Карточка',
                'verbose_name_plural': 'Карточки',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', 'level'], name='cards_card_user_id_efb68e_idx'), models.Index(fields=['user', '-created_at'], name='cards_card_user_id_4d7ac7_idx')],
            },
        ),
    ]
