# Generated by Django 4.2.7 on 2025-12-05 17:25

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cards', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('next_review_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Следующее повторение')),
                ('interval', models.IntegerField(default=1, verbose_name='Интервал (дни)')),
                ('repetitions', models.IntegerField(default=0, verbose_name='Количество повторений')),
                ('easiness_factor', models.FloatField(default=2.5, verbose_name='Фактор легкости')),
                ('last_reviewed_at', models.DateTimeField(blank=True, null=True, verbose_name='Последнее повторение')),
                ('card', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='schedule', to='cards.card', verbose_name='Карточка')),
            ],
            options={
                'verbose_name': 'Расписание',
                'verbose_name_plural': 'Расписания',
                'ordering': ['next_review_at'],
                'indexes': [models.Index(fields=['next_review_at'], name='schedules_s_next_re_926f91_idx'), models.Index(fields=['card'], name='schedules_s_card_id_a3d3d2_idx')],
            },
        ),
    ]
